eureka:
  client:
    serviceUrl:
      defaultZone:http://localhost:6001/Eureka
spring:
  cloud:
    gateway:
      routes:
        - id:microservice-Utilisateur
          uri:lb://GestionUtilistateur
          predicates:
            - path= /utilisateur/**
          filter:
            - RewritePath=/utilisateur/(?<path>.*), /$\{path}
            
         - id:microservice-Abonnement
          uri:lb://GestionAbonnement
          predicates:
            - path= /abonnement/**
          filter:
            - RewritePath=/projet/(?<path>.*), /$\{path}     
      
